import { ClusterProvider } from "@/components/cluster/cluster-data-access";
import { Sidebar } from "@/components/sidebar";
import { SolanaProvider } from "@/components/solana/solana-provider";
import { TopBar } from "@/components/top-bar";
import { ClerkProvider, SignInButton, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import { ReactQueryProvider } from "./react-query-provider";
export const metadata = {
  title: "demo",
  description: "Generated by create-solana-dapp",
};

const links: { label: string; path: string }[] = [
  { label: "Account", path: "/account" },
  { label: "Clusters", path: "/clusters" },
  { label: "Demo Program", path: "/demo" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            <SignInButton />
          </SignedOut>

          <ReactQueryProvider>
            <ClusterProvider>
              <SolanaProvider>
                <div className="flex h-screen">
                  <Sidebar />
                  <div className="flex-1 flex flex-col overflow-hidden">
                    <TopBar />
                    <main className="flex-1 overflow-x-hidden overflow-y-auto p-4">
                      {children}
                    </main>
                  </div>
                </div>
              </SolanaProvider>
            </ClusterProvider>
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
